# ===========================================
# Secret - Credentials sensibles
# ===========================================
apiVersion: v1
kind: Secret
metadata:
  name: audit-management-secret
  namespace: audit-app
  labels:
    app: audit-management
type: Opaque
# Les valeurs sont encod√©es en base64
# echo -n 'postgres' | base64 = cG9zdGdyZXM=
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=

---
# ===========================================
# Secret pour PostgreSQL
# ===========================================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: audit-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: YXVkaXRkYg==
